# SEO settings
title: The Three Laws Blog
description: "A blog about Artificial Intelligence regulation"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: 
baseurl: "/simplest"
# baseurl: null

google_analytics: 
repo: 
disqus_shortname: 

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Alex Ferguson
  job      : Attorney
  bio      : "Attorney from the Bamboo Law Group, PLLC that is interested in Artificial Intelligence and the future."
  thumb    : /images/author.jpg
  email    : test@gmail.com
  url      : http://bamboolawgroup.com
  github   : 
  twitter  : 
  facebook : 
  linkedin : 

# social settings
og_locale: "pt_BR"
twitter_card: "summary_large_image"
twitter_site: ""

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : ai-basics
    title: AI Basics Series
  - slug : ai-regulations
    title: AI Regulations

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]

